name: oatto_ecommerce_statemanagement
description: "This is my Portfolio Oatto"

publish_to: 'none' 

version: 1.0.0+1

environment:
   sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  circle_nav_bar: ^2.0.1+1
  google_fonts: ^5.1.0
  another_flutter_splash_screen: ^1.2.0
  animated_bottom_navigation_bar: ^1.1.0+1
  url_launcher: ^6.2.5
  carousel_slider: ^4.2.1
  page_transition: ^2.1.0
  provider: ^6.1.2
  uuid: ^4.3.3
  image_picker: ^1.0.7
  intl: ^0.19.0
  http: ^1.2.0
  quickalert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/app-1/
    - assets/images/app-2/

  